version: '3.9'
services:
  backend:
    build: ./backEnd
    container_name: ebytr_backend
    ports:
      - 3001:3001
    platform: linux/x86_64
    restart: 'always'
    volumes:
      - './backEnd/src:/app/src'
    depends_on:
      - db

  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'