version: '3.9'
services:
  db:
    image: mysql:8.0.21
    platform: linux/x86_64
    container_name: db
    ports:
      - 3002:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: 'always'